### ISSUE TITLE
clicking on menu in mobile view jumps the scroll position

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/GOLD#25]
jumping scroll position is a big no no for sane people :)

**Comment by TrebBrennan** [comment]
Took me a bit to work out what this issue meant so I figured I would add some more info if helps.

**To replicate**

- On mobile. Scroll past the header (or down a bit) so that the 'Open menu' button is near the top of the view port.
- Tap the open menu button,
- The view jumps to the top of the page.

**Expected**
- The view remains in place and the menu opens.

**Comment by alex-page** [comment]
@TrebBrennan @dominikwilkowski  Maybe we can add a class after the menu has opened that give the container `height: 100%;`.

This menu is actually quite a tricky beast!
